package br.edu.ifpb.qmanager.entidade;

public enum TipoArquivo {
	// PROJETO
	PROJETO_RELATORIO_PARCIAL, 
	PROJETO_RELATORIO_FINAL, 
	PROJETO_INICIAL, 
	PROJETO_CORRIGIDO, 
	PROJETO_PARECER_COMISSAO_ETICA, 
	PROJETO_TERMO_CONSENTIMENTO_LIVRE, 
	PROJETO_COM_IDENTIFICACAO, 
	PROJETO_SEM_IDENTIFICACAO,
	// PARTICIPANTE DE PROJETO
	PARTICIPANTE_HISTORICO_ESCOLAR, 
	PARTICIPANTE_TERMO_VOLUNTARIADO, 
	PARTICIPANTE_PLANO_TRABALHO, 
	PARTICIPANTE_BOLSISTA_DECLARACAO_VICULO;
}